In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Iris.csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
duplicate = df[df.duplicated()]
duplicate

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [8]:
df = df.drop(columns = ["Id"])

In [9]:
df['Species'] = df['Species'].map({'Iris-setosa' : 0 , 'Iris-versicolor' : 1 , 'Iris-virginica' : 2})

In [10]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [11]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\hp world\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\hp world\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\hp world\anaconda3\lib\site-packages (from xgboost) (1.15.3)

In [12]:
from sklearn.model_selection import train_test_split
import xgboost as xgb

In [13]:
X=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=df[['Species']]

In [14]:
X_test,X_train,y_test,y_train = train_test_split(X,y,test_size = 0.2,random_state=400)

In [15]:
model = xgb.XGBClassifier(random_state=400)

In [16]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [17]:
y_predict = model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

In [19]:
accuracy = accuracy_score(y_test, y_predict)
accuracy

0.9166666666666666

In [20]:
recall = recall_score (y_test, y_predict, average = 'macro')
recall

0.9184959349593496

In [21]:
precision = precision_score(y_test, y_predict, average= 'macro')
precision

0.9216450216450216

In [22]:
f1 = f1_score(y_test, y_predict, average= 'macro')
f1

0.9151582955504524

In [23]:
def prediction_flower():
    SepalLengthCm= float(input("Enter the length of sepal= "))
    SepalWidthCm= float(input("Enter the width of sepal = "))
    PetalLengthCm= float(input("Enter the length of petal = "))
    PetalWidthCm= float(input("Enter the width of petal = "))

    flower_data = pd.DataFrame([[SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm]], columns = ['SepalLengthCm' , 'SepalWidthCm' , 'PetalLengthCm' , 'PetalWidthCm'],)
    print("---- Result ----")
    prediction = model.predict(flower_data)[0]
    if prediction == 0 :
        print("Flower is Iris-setosa")
    elif prediction == 1 :
        print("Flower is Iris-versicolor")
    else :
        print("Flower is Iris-verginica")

In [24]:
prediction_flower()

Enter the length of sepal=  5.2
Enter the width of sepal =  3.5
Enter the length of petal =  1.4
Enter the width of petal =  0.7

---- Result ----
Flower is Iris-setosa

---- Result ----
Flower is Iris-versicolor

In [25]:
import pickle

# Export your trained XGBoost model to a static file
with open('flower_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model successfully saved to 'flower_model.pkl'!")

Model successfully saved to 'flower_model.pkl'!